import type { AnswerKey, PooledTriviaQuestion } from "@world-cup-game/types";
import { InsufficientPoolError, selectDailyQuestions } from "./selectDailyQuestions";
import { seededRandom, seededShuffle } from "./seededRandom";

export interface DayPlan {
  activeDate: string;
  questions: PooledTriviaQuestion[];
}

export interface ScheduleGap {
  activeDate: string;
  reason: string;
  availableNations: number;
  needed: number;
}

export interface ScheduleResult {
  schedule: DayPlan[];
  gaps: ScheduleGap[];
}

const OPTION_KEYS: readonly AnswerKey[] = ["A", "B", "C", "D"];

/**
 * Deterministically reorder a question's four option labels across the fixed
 * A–D slots (seeded by `seedKey`) and recompute `correctAnswerKey`. Index-based
 * so it is robust to duplicate labels. Same seedKey → same arrangement.
 */
export function withShuffledOptions(
  question: PooledTriviaQuestion,
  seedKey: string,
): PooledTriviaQuestion {
  const correctOldIndex = question.answerOptions.findIndex(
    (o) => o.key === question.correctAnswerKey,
  );
  if (correctOldIndex < 0) {
    throw new Error(
      `Question ${question.id} has no option for correctAnswerKey ${question.correctAnswerKey}`,
    );
  }
  const order = seededShuffle(
    question.answerOptions.map((_, i) => i),
    seededRandom(seedKey),
  );
  const answerOptions = order.map((oldIndex, newIndex) => ({
    key: OPTION_KEYS[newIndex] as AnswerKey,
    label: question.answerOptions[oldIndex]!.label,
  }));
  const correctNewIndex = order.indexOf(correctOldIndex);
  return {
    ...question,
    answerOptions,
    correctAnswerKey: OPTION_KEYS[correctNewIndex] as AnswerKey,
  };
}

/** Add `n` whole UTC days to an ISO `YYYY-MM-DD` date. */
export function addDays(isoDate: string, n: number): string {
  const d = new Date(`${isoDate}T00:00:00Z`);
  d.setUTCDate(d.getUTCDate() + n);
  return d.toISOString().slice(0, 10);
}

/**
 * Build a daily schedule from `startDate` (inclusive) for `days` days. Each day
 * gets `count` distinct-nation WC questions. Questions are not reused across the
 * horizon (unless reuseQuestions). Days that cannot be filled are returned as
 * gaps rather than throwing (report mode).
 */
export function generateTriviaSchedule(params: {
  pool: readonly PooledTriviaQuestion[];
  wcNationCodes: ReadonlySet<string>;
  startDate: string;
  days: number;
  count?: number;
  reuseQuestions?: boolean;
}): ScheduleResult {
  const count = params.count ?? 3;
  const reuse = params.reuseQuestions ?? false;
  const used = new Set<string>();
  const schedule: DayPlan[] = [];
  const gaps: ScheduleGap[] = [];

  for (let i = 0; i < params.days; i++) {
    const activeDate = addDays(params.startDate, i);
    try {
      const questions = selectDailyQuestions(params.pool, activeDate, count, {
        wcNationCodes: params.wcNationCodes,
        excludeQuestionIds: reuse ? undefined : used,
      }).map((question) => withShuffledOptions(question, `${activeDate}:${question.id}`));
      schedule.push({ activeDate, questions });
      if (!reuse) for (const q of questions) used.add(q.id);
    } catch (err) {
      if (err instanceof InsufficientPoolError) {
        gaps.push({
          activeDate,
          reason: err.reason,
          availableNations: err.availableNations,
          needed: err.needed,
        });
      } else {
        throw err;
      }
    }
  }

  return { schedule, gaps };
}

function sqlEscape(value: string): string {
  return value.replace(/'/g, "''");
}

/** Render an idempotent upsert seed for the given schedule. */
export function renderScheduleSql(schedule: readonly DayPlan[]): string {
  const rows: string[] = [];
  for (const day of schedule) {
    day.questions.forEach((q, idx) => {
      const order = idx + 1;
      const options = sqlEscape(JSON.stringify(q.answerOptions));
      rows.push(
        `  ('${day.activeDate}', ${order}, '${sqlEscape(q.question)}', ` +
          `'${options}'::jsonb, '${q.correctAnswerKey}', ` +
          `'${sqlEscape(q.explanation)}', '${sqlEscape(q.difficulty)}', '${sqlEscape(q.nationCode)}')`,
      );
    });
  }
  if (rows.length === 0) {
    return "-- GENERATED by generateTriviaSeed — no schedulable days (all gaps).\n";
  }
  return [
    "-- GENERATED by generateTriviaSeed — do not edit by hand.",
    "insert into public.trivia_questions (",
    "  active_date, question_order, question, answer_options,",
    "  correct_answer_key, explanation, difficulty, nation_code",
    ") values",
    rows.join(",\n"),
    "on conflict (active_date, question_order) do update set",
    "  question = excluded.question,",
    "  answer_options = excluded.answer_options,",
    "  correct_answer_key = excluded.correct_answer_key,",
    "  explanation = excluded.explanation,",
    "  difficulty = excluded.difficulty,",
    "  nation_code = excluded.nation_code;",
    "",
  ].join("\n");
}
