/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in a full app setup. It is committed here so
// the scaffold can typecheck before the first `next dev` run.
