// AUTO-GENERATED by scripts/build-schedule.mjs. Do not edit by hand.
// Regenerate with: pnpm build:schedule (source: src/data/worldcup.json)

import type { Fixture } from "./schedule";

export const WORLD_CUP_FIXTURES: Fixture[] = [
  {
    "num": 1,
    "round": "Matchday 1",
    "stage": "group",
    "group": "Group A",
    "kickoffUtc": "2026-06-11T19:00:00.000Z",
    "team1": "Mexico",
    "team2": "South Africa",
    "venueCity": "Mexico City"
  },
  {
    "num": 2,
    "round": "Matchday 1",
    "stage": "group",
    "group": "Group A",
    "kickoffUtc": "2026-06-12T02:00:00.000Z",
    "team1": "South Korea",
    "team2": "Czech Republic",
    "venueCity": "Guadalajara (Zapopan)"
  },
  {
    "num": 3,
    "round": "Matchday 2",
    "stage": "group",
    "group": "Group B",
    "kickoffUtc": "2026-06-12T19:00:00.000Z",
    "team1": "Canada",
    "team2": "Bosnia & Herzegovina",
    "venueCity": "Toronto"
  },
  {
    "num": 4,
    "round": "Matchday 2",
    "stage": "group",
    "group": "Group D",
    "kickoffUtc": "2026-06-13T01:00:00.000Z",
    "team1": "USA",
    "team2": "Paraguay",
    "venueCity": "Los Angeles (Inglewood)"
  },
  {
    "num": 5,
    "round": "Matchday 3",
    "stage": "group",
    "group": "Group B",
    "kickoffUtc": "2026-06-13T19:00:00.000Z",
    "team1": "Qatar",
    "team2": "Switzerland",
    "venueCity": "San Francisco Bay Area (Santa Clara)"
  },
  {
    "num": 6,
    "round": "Matchday 3",
    "stage": "group",
    "group": "Group C",
    "kickoffUtc": "2026-06-13T22:00:00.000Z",
    "team1": "Brazil",
    "team2": "Morocco",
    "venueCity": "New York/New Jersey (East Rutherford)"
  },
  {
    "num": 7,
    "round": "Matchday 3",
    "stage": "group",
    "group": "Group C",
    "kickoffUtc": "2026-06-14T01:00:00.000Z",
    "team1": "Haiti",
    "team2": "Scotland",
    "venueCity": "Boston (Foxborough)"
  },
  {
    "num": 8,
    "round": "Matchday 3",
    "stage": "group",
    "group": "Group D",
    "kickoffUtc": "2026-06-14T04:00:00.000Z",
    "team1": "Australia",
    "team2": "Turkey",
    "venueCity": "Vancouver"
  },
  {
    "num": 9,
    "round": "Matchday 4",
    "stage": "group",
    "group": "Group E",
    "kickoffUtc": "2026-06-14T17:00:00.000Z",
    "team1": "Germany",
    "team2": "Curaçao",
    "venueCity": "Houston"
  },
  {
    "num": 10,
    "round": "Matchday 4",
    "stage": "group",
    "group": "Group F",
    "kickoffUtc": "2026-06-14T20:00:00.000Z",
    "team1": "Netherlands",
    "team2": "Japan",
    "venueCity": "Dallas (Arlington)"
  },
  {
    "num": 11,
    "round": "Matchday 4",
    "stage": "group",
    "group": "Group E",
    "kickoffUtc": "2026-06-14T23:00:00.000Z",
    "team1": "Ivory Coast",
    "team2": "Ecuador",
    "venueCity": "Philadelphia"
  },
  {
    "num": 12,
    "round": "Matchday 4",
    "stage": "group",
    "group": "Group F",
    "kickoffUtc": "2026-06-15T02:00:00.000Z",
    "team1": "Sweden",
    "team2": "Tunisia",
    "venueCity": "Monterrey (Guadalupe)"
  },
  {
    "num": 13,
    "round": "Matchday 5",
    "stage": "group",
    "group": "Group H",
    "kickoffUtc": "2026-06-15T16:00:00.000Z",
    "team1": "Spain",
    "team2": "Cape Verde",
    "venueCity": "Atlanta"
  },
  {
    "num": 14,
    "round": "Matchday 5",
    "stage": "group",
    "group": "Group G",
    "kickoffUtc": "2026-06-15T19:00:00.000Z",
    "team1": "Belgium",
    "team2": "Egypt",
    "venueCity": "Seattle"
  },
  {
    "num": 15,
    "round": "Matchday 5",
    "stage": "group",
    "group": "Group H",
    "kickoffUtc": "2026-06-15T22:00:00.000Z",
    "team1": "Saudi Arabia",
    "team2": "Uruguay",
    "venueCity": "Miami (Miami Gardens)"
  },
  {
    "num": 16,
    "round": "Matchday 5",
    "stage": "group",
    "group": "Group G",
    "kickoffUtc": "2026-06-16T01:00:00.000Z",
    "team1": "Iran",
    "team2": "New Zealand",
    "venueCity": "Los Angeles (Inglewood)"
  },
  {
    "num": 17,
    "round": "Matchday 6",
    "stage": "group",
    "group": "Group I",
    "kickoffUtc": "2026-06-16T19:00:00.000Z",
    "team1": "France",
    "team2": "Senegal",
    "venueCity": "New York/New Jersey (East Rutherford)"
  },
  {
    "num": 18,
    "round": "Matchday 6",
    "stage": "group",
    "group": "Group I",
    "kickoffUtc": "2026-06-16T22:00:00.000Z",
    "team1": "Iraq",
    "team2": "Norway",
    "venueCity": "Boston (Foxborough)"
  },
  {
    "num": 19,
    "round": "Matchday 6",
    "stage": "group",
    "group": "Group J",
    "kickoffUtc": "2026-06-17T01:00:00.000Z",
    "team1": "Argentina",
    "team2": "Algeria",
    "venueCity": "Kansas City"
  },
  {
    "num": 20,
    "round": "Matchday 6",
    "stage": "group",
    "group": "Group J",
    "kickoffUtc": "2026-06-17T04:00:00.000Z",
    "team1": "Austria",
    "team2": "Jordan",
    "venueCity": "San Francisco Bay Area (Santa Clara)"
  },
  {
    "num": 21,
    "round": "Matchday 7",
    "stage": "group",
    "group": "Group K",
    "kickoffUtc": "2026-06-17T17:00:00.000Z",
    "team1": "Portugal",
    "team2": "DR Congo",
    "venueCity": "Houston"
  },
  {
    "num": 22,
    "round": "Matchday 7",
    "stage": "group",
    "group": "Group L",
    "kickoffUtc": "2026-06-17T20:00:00.000Z",
    "team1": "England",
    "team2": "Croatia",
    "venueCity": "Dallas (Arlington)"
  },
  {
    "num": 23,
    "round": "Matchday 7",
    "stage": "group",
    "group": "Group L",
    "kickoffUtc": "2026-06-17T23:00:00.000Z",
    "team1": "Ghana",
    "team2": "Panama",
    "venueCity": "Toronto"
  },
  {
    "num": 24,
    "round": "Matchday 7",
    "stage": "group",
    "group": "Group K",
    "kickoffUtc": "2026-06-18T02:00:00.000Z",
    "team1": "Uzbekistan",
    "team2": "Colombia",
    "venueCity": "Mexico City"
  },
  {
    "num": 25,
    "round": "Matchday 8",
    "stage": "group",
    "group": "Group A",
    "kickoffUtc": "2026-06-18T16:00:00.000Z",
    "team1": "Czech Republic",
    "team2": "South Africa",
    "venueCity": "Atlanta"
  },
  {
    "num": 26,
    "round": "Matchday 8",
    "stage": "group",
    "group": "Group B",
    "kickoffUtc": "2026-06-18T19:00:00.000Z",
    "team1": "Switzerland",
    "team2": "Bosnia & Herzegovina",
    "venueCity": "Los Angeles (Inglewood)"
  },
  {
    "num": 27,
    "round": "Matchday 8",
    "stage": "group",
    "group": "Group B",
    "kickoffUtc": "2026-06-18T22:00:00.000Z",
    "team1": "Canada",
    "team2": "Qatar",
    "venueCity": "Vancouver"
  },
  {
    "num": 28,
    "round": "Matchday 8",
    "stage": "group",
    "group": "Group A",
    "kickoffUtc": "2026-06-19T01:00:00.000Z",
    "team1": "Mexico",
    "team2": "South Korea",
    "venueCity": "Guadalajara (Zapopan)"
  },
  {
    "num": 29,
    "round": "Matchday 9",
    "stage": "group",
    "group": "Group D",
    "kickoffUtc": "2026-06-19T19:00:00.000Z",
    "team1": "USA",
    "team2": "Australia",
    "venueCity": "Seattle"
  },
  {
    "num": 30,
    "round": "Matchday 9",
    "stage": "group",
    "group": "Group C",
    "kickoffUtc": "2026-06-19T22:00:00.000Z",
    "team1": "Scotland",
    "team2": "Morocco",
    "venueCity": "Boston (Foxborough)"
  },
  {
    "num": 31,
    "round": "Matchday 9",
    "stage": "group",
    "group": "Group C",
    "kickoffUtc": "2026-06-20T00:30:00.000Z",
    "team1": "Brazil",
    "team2": "Haiti",
    "venueCity": "Philadelphia"
  },
  {
    "num": 32,
    "round": "Matchday 9",
    "stage": "group",
    "group": "Group D",
    "kickoffUtc": "2026-06-20T03:00:00.000Z",
    "team1": "Turkey",
    "team2": "Paraguay",
    "venueCity": "San Francisco Bay Area (Santa Clara)"
  },
  {
    "num": 33,
    "round": "Matchday 10",
    "stage": "group",
    "group": "Group F",
    "kickoffUtc": "2026-06-20T17:00:00.000Z",
    "team1": "Netherlands",
    "team2": "Sweden",
    "venueCity": "Houston"
  },
  {
    "num": 34,
    "round": "Matchday 10",
    "stage": "group",
    "group": "Group E",
    "kickoffUtc": "2026-06-20T20:00:00.000Z",
    "team1": "Germany",
    "team2": "Ivory Coast",
    "venueCity": "Toronto"
  },
  {
    "num": 35,
    "round": "Matchday 10",
    "stage": "group",
    "group": "Group E",
    "kickoffUtc": "2026-06-21T00:00:00.000Z",
    "team1": "Ecuador",
    "team2": "Curaçao",
    "venueCity": "Kansas City"
  },
  {
    "num": 36,
    "round": "Matchday 10",
    "stage": "group",
    "group": "Group F",
    "kickoffUtc": "2026-06-21T04:00:00.000Z",
    "team1": "Tunisia",
    "team2": "Japan",
    "venueCity": "Monterrey (Guadalupe)"
  },
  {
    "num": 37,
    "round": "Matchday 11",
    "stage": "group",
    "group": "Group H",
    "kickoffUtc": "2026-06-21T16:00:00.000Z",
    "team1": "Spain",
    "team2": "Saudi Arabia",
    "venueCity": "Atlanta"
  },
  {
    "num": 38,
    "round": "Matchday 11",
    "stage": "group",
    "group": "Group G",
    "kickoffUtc": "2026-06-21T19:00:00.000Z",
    "team1": "Belgium",
    "team2": "Iran",
    "venueCity": "Los Angeles (Inglewood)"
  },
  {
    "num": 39,
    "round": "Matchday 11",
    "stage": "group",
    "group": "Group H",
    "kickoffUtc": "2026-06-21T22:00:00.000Z",
    "team1": "Uruguay",
    "team2": "Cape Verde",
    "venueCity": "Miami (Miami Gardens)"
  },
  {
    "num": 40,
    "round": "Matchday 11",
    "stage": "group",
    "group": "Group G",
    "kickoffUtc": "2026-06-22T01:00:00.000Z",
    "team1": "New Zealand",
    "team2": "Egypt",
    "venueCity": "Vancouver"
  },
  {
    "num": 41,
    "round": "Matchday 12",
    "stage": "group",
    "group": "Group J",
    "kickoffUtc": "2026-06-22T17:00:00.000Z",
    "team1": "Argentina",
    "team2": "Austria",
    "venueCity": "Dallas (Arlington)"
  },
  {
    "num": 42,
    "round": "Matchday 12",
    "stage": "group",
    "group": "Group I",
    "kickoffUtc": "2026-06-22T21:00:00.000Z",
    "team1": "France",
    "team2": "Iraq",
    "venueCity": "Philadelphia"
  },
  {
    "num": 43,
    "round": "Matchday 12",
    "stage": "group",
    "group": "Group I",
    "kickoffUtc": "2026-06-23T00:00:00.000Z",
    "team1": "Norway",
    "team2": "Senegal",
    "venueCity": "New York/New Jersey (East Rutherford)"
  },
  {
    "num": 44,
    "round": "Matchday 12",
    "stage": "group",
    "group": "Group J",
    "kickoffUtc": "2026-06-23T03:00:00.000Z",
    "team1": "Jordan",
    "team2": "Algeria",
    "venueCity": "San Francisco Bay Area (Santa Clara)"
  },
  {
    "num": 45,
    "round": "Matchday 13",
    "stage": "group",
    "group": "Group K",
    "kickoffUtc": "2026-06-23T17:00:00.000Z",
    "team1": "Portugal",
    "team2": "Uzbekistan",
    "venueCity": "Houston"
  },
  {
    "num": 46,
    "round": "Matchday 13",
    "stage": "group",
    "group": "Group L",
    "kickoffUtc": "2026-06-23T20:00:00.000Z",
    "team1": "England",
    "team2": "Ghana",
    "venueCity": "Boston (Foxborough)"
  },
  {
    "num": 47,
    "round": "Matchday 13",
    "stage": "group",
    "group": "Group L",
    "kickoffUtc": "2026-06-23T23:00:00.000Z",
    "team1": "Panama",
    "team2": "Croatia",
    "venueCity": "Toronto"
  },
  {
    "num": 48,
    "round": "Matchday 13",
    "stage": "group",
    "group": "Group K",
    "kickoffUtc": "2026-06-24T02:00:00.000Z",
    "team1": "Colombia",
    "team2": "DR Congo",
    "venueCity": "Guadalajara (Zapopan)"
  },
  {
    "num": 49,
    "round": "Matchday 14",
    "stage": "group",
    "group": "Group B",
    "kickoffUtc": "2026-06-24T19:00:00.000Z",
    "team1": "Bosnia & Herzegovina",
    "team2": "Qatar",
    "venueCity": "Seattle"
  },
  {
    "num": 50,
    "round": "Matchday 14",
    "stage": "group",
    "group": "Group B",
    "kickoffUtc": "2026-06-24T19:00:00.000Z",
    "team1": "Switzerland",
    "team2": "Canada",
    "venueCity": "Vancouver"
  },
  {
    "num": 51,
    "round": "Matchday 14",
    "stage": "group",
    "group": "Group C",
    "kickoffUtc": "2026-06-24T22:00:00.000Z",
    "team1": "Morocco",
    "team2": "Haiti",
    "venueCity": "Atlanta"
  },
  {
    "num": 52,
    "round": "Matchday 14",
    "stage": "group",
    "group": "Group C",
    "kickoffUtc": "2026-06-24T22:00:00.000Z",
    "team1": "Scotland",
    "team2": "Brazil",
    "venueCity": "Miami (Miami Gardens)"
  },
  {
    "num": 53,
    "round": "Matchday 14",
    "stage": "group",
    "group": "Group A",
    "kickoffUtc": "2026-06-25T01:00:00.000Z",
    "team1": "Czech Republic",
    "team2": "Mexico",
    "venueCity": "Mexico City"
  },
  {
    "num": 54,
    "round": "Matchday 14",
    "stage": "group",
    "group": "Group A",
    "kickoffUtc": "2026-06-25T01:00:00.000Z",
    "team1": "South Africa",
    "team2": "South Korea",
    "venueCity": "Monterrey (Guadalupe)"
  },
  {
    "num": 55,
    "round": "Matchday 15",
    "stage": "group",
    "group": "Group E",
    "kickoffUtc": "2026-06-25T20:00:00.000Z",
    "team1": "Ecuador",
    "team2": "Germany",
    "venueCity": "New York/New Jersey (East Rutherford)"
  },
  {
    "num": 56,
    "round": "Matchday 15",
    "stage": "group",
    "group": "Group E",
    "kickoffUtc": "2026-06-25T20:00:00.000Z",
    "team1": "Curaçao",
    "team2": "Ivory Coast",
    "venueCity": "Philadelphia"
  },
  {
    "num": 57,
    "round": "Matchday 15",
    "stage": "group",
    "group": "Group F",
    "kickoffUtc": "2026-06-25T23:00:00.000Z",
    "team1": "Japan",
    "team2": "Sweden",
    "venueCity": "Dallas (Arlington)"
  },
  {
    "num": 58,
    "round": "Matchday 15",
    "stage": "group",
    "group": "Group F",
    "kickoffUtc": "2026-06-25T23:00:00.000Z",
    "team1": "Tunisia",
    "team2": "Netherlands",
    "venueCity": "Kansas City"
  },
  {
    "num": 59,
    "round": "Matchday 15",
    "stage": "group",
    "group": "Group D",
    "kickoffUtc": "2026-06-26T02:00:00.000Z",
    "team1": "Turkey",
    "team2": "USA",
    "venueCity": "Los Angeles (Inglewood)"
  },
  {
    "num": 60,
    "round": "Matchday 15",
    "stage": "group",
    "group": "Group D",
    "kickoffUtc": "2026-06-26T02:00:00.000Z",
    "team1": "Paraguay",
    "team2": "Australia",
    "venueCity": "San Francisco Bay Area (Santa Clara)"
  },
  {
    "num": 61,
    "round": "Matchday 16",
    "stage": "group",
    "group": "Group I",
    "kickoffUtc": "2026-06-26T19:00:00.000Z",
    "team1": "Norway",
    "team2": "France",
    "venueCity": "Boston (Foxborough)"
  },
  {
    "num": 62,
    "round": "Matchday 16",
    "stage": "group",
    "group": "Group I",
    "kickoffUtc": "2026-06-26T19:00:00.000Z",
    "team1": "Senegal",
    "team2": "Iraq",
    "venueCity": "Toronto"
  },
  {
    "num": 63,
    "round": "Matchday 16",
    "stage": "group",
    "group": "Group H",
    "kickoffUtc": "2026-06-27T00:00:00.000Z",
    "team1": "Uruguay",
    "team2": "Spain",
    "venueCity": "Guadalajara (Zapopan)"
  },
  {
    "num": 64,
    "round": "Matchday 16",
    "stage": "group",
    "group": "Group H",
    "kickoffUtc": "2026-06-27T00:00:00.000Z",
    "team1": "Cape Verde",
    "team2": "Saudi Arabia",
    "venueCity": "Houston"
  },
  {
    "num": 65,
    "round": "Matchday 16",
    "stage": "group",
    "group": "Group G",
    "kickoffUtc": "2026-06-27T03:00:00.000Z",
    "team1": "Egypt",
    "team2": "Iran",
    "venueCity": "Seattle"
  },
  {
    "num": 66,
    "round": "Matchday 16",
    "stage": "group",
    "group": "Group G",
    "kickoffUtc": "2026-06-27T03:00:00.000Z",
    "team1": "New Zealand",
    "team2": "Belgium",
    "venueCity": "Vancouver"
  },
  {
    "num": 67,
    "round": "Matchday 17",
    "stage": "group",
    "group": "Group L",
    "kickoffUtc": "2026-06-27T21:00:00.000Z",
    "team1": "Panama",
    "team2": "England",
    "venueCity": "New York/New Jersey (East Rutherford)"
  },
  {
    "num": 68,
    "round": "Matchday 17",
    "stage": "group",
    "group": "Group L",
    "kickoffUtc": "2026-06-27T21:00:00.000Z",
    "team1": "Croatia",
    "team2": "Ghana",
    "venueCity": "Philadelphia"
  },
  {
    "num": 69,
    "round": "Matchday 17",
    "stage": "group",
    "group": "Group K",
    "kickoffUtc": "2026-06-27T23:30:00.000Z",
    "team1": "DR Congo",
    "team2": "Uzbekistan",
    "venueCity": "Atlanta"
  },
  {
    "num": 70,
    "round": "Matchday 17",
    "stage": "group",
    "group": "Group K",
    "kickoffUtc": "2026-06-27T23:30:00.000Z",
    "team1": "Colombia",
    "team2": "Portugal",
    "venueCity": "Miami (Miami Gardens)"
  },
  {
    "num": 71,
    "round": "Matchday 17",
    "stage": "group",
    "group": "Group J",
    "kickoffUtc": "2026-06-28T02:00:00.000Z",
    "team1": "Jordan",
    "team2": "Argentina",
    "venueCity": "Dallas (Arlington)"
  },
  {
    "num": 72,
    "round": "Matchday 17",
    "stage": "group",
    "group": "Group J",
    "kickoffUtc": "2026-06-28T02:00:00.000Z",
    "team1": "Algeria",
    "team2": "Austria",
    "venueCity": "Kansas City"
  },
  {
    "num": 73,
    "round": "Round of 32",
    "stage": "r32",
    "group": null,
    "kickoffUtc": "2026-06-28T19:00:00.000Z",
    "team1": "2A",
    "team2": "2B",
    "venueCity": "Los Angeles (Inglewood)"
  },
  {
    "num": 76,
    "round": "Round of 32",
    "stage": "r32",
    "group": null,
    "kickoffUtc": "2026-06-29T17:00:00.000Z",
    "team1": "1C",
    "team2": "2F",
    "venueCity": "Houston"
  },
  {
    "num": 74,
    "round": "Round of 32",
    "stage": "r32",
    "group": null,
    "kickoffUtc": "2026-06-29T20:30:00.000Z",
    "team1": "1E",
    "team2": "3A/B/C/D/F",
    "venueCity": "Boston (Foxborough)"
  },
  {
    "num": 75,
    "round": "Round of 32",
    "stage": "r32",
    "group": null,
    "kickoffUtc": "2026-06-30T01:00:00.000Z",
    "team1": "1F",
    "team2": "2C",
    "venueCity": "Monterrey (Guadalupe)"
  },
  {
    "num": 78,
    "round": "Round of 32",
    "stage": "r32",
    "group": null,
    "kickoffUtc": "2026-06-30T17:00:00.000Z",
    "team1": "2E",
    "team2": "2I",
    "venueCity": "Dallas (Arlington)"
  },
  {
    "num": 77,
    "round": "Round of 32",
    "stage": "r32",
    "group": null,
    "kickoffUtc": "2026-06-30T21:00:00.000Z",
    "team1": "1I",
    "team2": "3C/D/F/G/H",
    "venueCity": "New York/New Jersey (East Rutherford)"
  },
  {
    "num": 79,
    "round": "Round of 32",
    "stage": "r32",
    "group": null,
    "kickoffUtc": "2026-07-01T01:00:00.000Z",
    "team1": "1A",
    "team2": "3C/E/F/H/I",
    "venueCity": "Mexico City"
  },
  {
    "num": 80,
    "round": "Round of 32",
    "stage": "r32",
    "group": null,
    "kickoffUtc": "2026-07-01T16:00:00.000Z",
    "team1": "1L",
    "team2": "3E/H/I/J/K",
    "venueCity": "Atlanta"
  },
  {
    "num": 82,
    "round": "Round of 32",
    "stage": "r32",
    "group": null,
    "kickoffUtc": "2026-07-01T20:00:00.000Z",
    "team1": "1G",
    "team2": "3A/E/H/I/J",
    "venueCity": "Seattle"
  },
  {
    "num": 81,
    "round": "Round of 32",
    "stage": "r32",
    "group": null,
    "kickoffUtc": "2026-07-02T00:00:00.000Z",
    "team1": "1D",
    "team2": "3B/E/F/I/J",
    "venueCity": "San Francisco Bay Area (Santa Clara)"
  },
  {
    "num": 84,
    "round": "Round of 32",
    "stage": "r32",
    "group": null,
    "kickoffUtc": "2026-07-02T19:00:00.000Z",
    "team1": "1H",
    "team2": "2J",
    "venueCity": "Los Angeles (Inglewood)"
  },
  {
    "num": 83,
    "round": "Round of 32",
    "stage": "r32",
    "group": null,
    "kickoffUtc": "2026-07-02T23:00:00.000Z",
    "team1": "2K",
    "team2": "2L",
    "venueCity": "Toronto"
  },
  {
    "num": 85,
    "round": "Round of 32",
    "stage": "r32",
    "group": null,
    "kickoffUtc": "2026-07-03T03:00:00.000Z",
    "team1": "1B",
    "team2": "3E/F/G/I/J",
    "venueCity": "Vancouver"
  },
  {
    "num": 88,
    "round": "Round of 32",
    "stage": "r32",
    "group": null,
    "kickoffUtc": "2026-07-03T18:00:00.000Z",
    "team1": "2D",
    "team2": "2G",
    "venueCity": "Dallas (Arlington)"
  },
  {
    "num": 86,
    "round": "Round of 32",
    "stage": "r32",
    "group": null,
    "kickoffUtc": "2026-07-03T22:00:00.000Z",
    "team1": "1J",
    "team2": "2H",
    "venueCity": "Miami (Miami Gardens)"
  },
  {
    "num": 87,
    "round": "Round of 32",
    "stage": "r32",
    "group": null,
    "kickoffUtc": "2026-07-04T01:30:00.000Z",
    "team1": "1K",
    "team2": "3D/E/I/J/L",
    "venueCity": "Kansas City"
  },
  {
    "num": 90,
    "round": "Round of 16",
    "stage": "r16",
    "group": null,
    "kickoffUtc": "2026-07-04T17:00:00.000Z",
    "team1": "W73",
    "team2": "W75",
    "venueCity": "Houston"
  },
  {
    "num": 89,
    "round": "Round of 16",
    "stage": "r16",
    "group": null,
    "kickoffUtc": "2026-07-04T21:00:00.000Z",
    "team1": "W74",
    "team2": "W77",
    "venueCity": "Philadelphia"
  },
  {
    "num": 91,
    "round": "Round of 16",
    "stage": "r16",
    "group": null,
    "kickoffUtc": "2026-07-05T20:00:00.000Z",
    "team1": "W76",
    "team2": "W78",
    "venueCity": "New York/New Jersey (East Rutherford)"
  },
  {
    "num": 92,
    "round": "Round of 16",
    "stage": "r16",
    "group": null,
    "kickoffUtc": "2026-07-06T00:00:00.000Z",
    "team1": "W79",
    "team2": "W80",
    "venueCity": "Mexico City"
  },
  {
    "num": 93,
    "round": "Round of 16",
    "stage": "r16",
    "group": null,
    "kickoffUtc": "2026-07-06T19:00:00.000Z",
    "team1": "W83",
    "team2": "W84",
    "venueCity": "Dallas (Arlington)"
  },
  {
    "num": 94,
    "round": "Round of 16",
    "stage": "r16",
    "group": null,
    "kickoffUtc": "2026-07-07T00:00:00.000Z",
    "team1": "W81",
    "team2": "W82",
    "venueCity": "Seattle"
  },
  {
    "num": 95,
    "round": "Round of 16",
    "stage": "r16",
    "group": null,
    "kickoffUtc": "2026-07-07T16:00:00.000Z",
    "team1": "W86",
    "team2": "W88",
    "venueCity": "Atlanta"
  },
  {
    "num": 96,
    "round": "Round of 16",
    "stage": "r16",
    "group": null,
    "kickoffUtc": "2026-07-07T20:00:00.000Z",
    "team1": "W85",
    "team2": "W87",
    "venueCity": "Vancouver"
  },
  {
    "num": 97,
    "round": "Quarter-final",
    "stage": "qf",
    "group": null,
    "kickoffUtc": "2026-07-09T20:00:00.000Z",
    "team1": "W89",
    "team2": "W90",
    "venueCity": "Boston (Foxborough)"
  },
  {
    "num": 98,
    "round": "Quarter-final",
    "stage": "qf",
    "group": null,
    "kickoffUtc": "2026-07-10T19:00:00.000Z",
    "team1": "W93",
    "team2": "W94",
    "venueCity": "Los Angeles (Inglewood)"
  },
  {
    "num": 99,
    "round": "Quarter-final",
    "stage": "qf",
    "group": null,
    "kickoffUtc": "2026-07-11T21:00:00.000Z",
    "team1": "W91",
    "team2": "W92",
    "venueCity": "Miami (Miami Gardens)"
  },
  {
    "num": 100,
    "round": "Quarter-final",
    "stage": "qf",
    "group": null,
    "kickoffUtc": "2026-07-12T01:00:00.000Z",
    "team1": "W95",
    "team2": "W96",
    "venueCity": "Kansas City"
  },
  {
    "num": 101,
    "round": "Semi-final",
    "stage": "sf",
    "group": null,
    "kickoffUtc": "2026-07-14T19:00:00.000Z",
    "team1": "W97",
    "team2": "W98",
    "venueCity": "Dallas (Arlington)"
  },
  {
    "num": 102,
    "round": "Semi-final",
    "stage": "sf",
    "group": null,
    "kickoffUtc": "2026-07-15T19:00:00.000Z",
    "team1": "W99",
    "team2": "W100",
    "venueCity": "Atlanta"
  },
  {
    "num": 103,
    "round": "Match for third place",
    "stage": "third",
    "group": null,
    "kickoffUtc": "2026-07-18T21:00:00.000Z",
    "team1": "L101",
    "team2": "L102",
    "venueCity": "Miami (Miami Gardens)"
  },
  {
    "num": 104,
    "round": "Final",
    "stage": "final",
    "group": null,
    "kickoffUtc": "2026-07-19T19:00:00.000Z",
    "team1": "W101",
    "team2": "W102",
    "venueCity": "New York/New Jersey (East Rutherford)"
  }
];
