// AUTO-GENERATED by scripts/build-schedule.mjs. Do not edit by hand.
// Regenerate with: pnpm build:schedule (source: src/data/worldcup.stadiums.json)

import type { Stadium } from "./stadiums";

export const WORLD_CUP_STADIUMS: Stadium[] = [
  {
    "city": "Vancouver",
    "name": "BC Place",
    "capacity": 54000,
    "cc": "ca",
    "timezone": "UTC-7",
    "lat": 49.27667,
    "lng": -123.11194
  },
  {
    "city": "Seattle",
    "name": "Lumen Field",
    "capacity": 69000,
    "cc": "us",
    "timezone": "UTC-7",
    "lat": 47.59528,
    "lng": -122.33167
  },
  {
    "city": "San Francisco Bay Area (Santa Clara)",
    "name": "Levi's Stadium",
    "capacity": 71000,
    "cc": "us",
    "timezone": "UTC-7",
    "lat": 37.403,
    "lng": -121.97
  },
  {
    "city": "Los Angeles (Inglewood)",
    "name": "SoFi Stadium",
    "capacity": 70000,
    "cc": "us",
    "timezone": "UTC-7",
    "lat": 33.953,
    "lng": -118.339
  },
  {
    "city": "Guadalajara (Zapopan)",
    "name": "Estadio Akron",
    "capacity": 48000,
    "cc": "mx",
    "timezone": "UTC-6",
    "lat": 20.68167,
    "lng": -103.46278
  },
  {
    "city": "Mexico City",
    "name": "Estadio Azteca",
    "capacity": 83000,
    "cc": "mx",
    "timezone": "UTC-6",
    "lat": 19.30306,
    "lng": -99.15056
  },
  {
    "city": "Monterrey (Guadalupe)",
    "name": "Estadio BBVA",
    "capacity": 53500,
    "cc": "mx",
    "timezone": "UTC-6",
    "lat": 25.66917,
    "lng": -100.24444
  },
  {
    "city": "Houston",
    "name": "NRG Stadium",
    "capacity": 72000,
    "cc": "us",
    "timezone": "UTC-5",
    "lat": 29.68472,
    "lng": -95.41083
  },
  {
    "city": "Dallas (Arlington)",
    "name": "AT&T Stadium",
    "capacity": 94000,
    "cc": "us",
    "timezone": "UTC-5",
    "lat": 32.74778,
    "lng": -97.09278
  },
  {
    "city": "Kansas City",
    "name": "Arrowhead Stadium",
    "capacity": 73000,
    "cc": "us",
    "timezone": "UTC-5",
    "lat": 39.04889,
    "lng": -94.48389
  },
  {
    "city": "Atlanta",
    "name": "Mercedes-Benz Stadium",
    "capacity": 75000,
    "cc": "us",
    "timezone": "UTC-4",
    "lat": 33.75556,
    "lng": -84.4
  },
  {
    "city": "Miami (Miami Gardens)",
    "name": "Hard Rock Stadium",
    "capacity": 65000,
    "cc": "us",
    "timezone": "UTC-4",
    "lat": 25.95806,
    "lng": -80.23889
  },
  {
    "city": "Toronto",
    "name": "BMO Field",
    "capacity": 45000,
    "cc": "ca",
    "timezone": "UTC-4",
    "lat": 43.63333,
    "lng": -79.41861
  },
  {
    "city": "Boston (Foxborough)",
    "name": "Gillette Stadium",
    "capacity": 65000,
    "cc": "us",
    "timezone": "UTC-4",
    "lat": 42.091,
    "lng": -71.264
  },
  {
    "city": "Philadelphia",
    "name": "Lincoln Financial Field",
    "capacity": 69000,
    "cc": "us",
    "timezone": "UTC-4",
    "lat": 39.90083,
    "lng": -75.1675
  },
  {
    "city": "New York/New Jersey (East Rutherford)",
    "name": "MetLife Stadium",
    "capacity": 82500,
    "cc": "us",
    "timezone": "UTC-4",
    "lat": 40.81353,
    "lng": -74.07436
  }
];
