insert into public.nations (code, name, flag_emoji, confederation, primary_color, secondary_color)
values
  ('USA', 'United States', '🇺🇸', 'CONCACAF', '#1F4E8C', '#C8102E'),
  ('MEX', 'Mexico', '🇲🇽', 'CONCACAF', '#006341', '#CE1126'),
  ('CAN', 'Canada', '🇨🇦', 'CONCACAF', '#D80621', '#FFFFFF'),
  ('CRC', 'Costa Rica', '🇨🇷', 'CONCACAF', '#002B7F', '#CE1126'),
  ('PAN', 'Panama', '🇵🇦', 'CONCACAF', '#005AA7', '#DA121A'),
  ('JAM', 'Jamaica', '🇯🇲', 'CONCACAF', '#009B3A', '#FED100'),
  ('HON', 'Honduras', '🇭🇳', 'CONCACAF', '#0073CF', '#FFFFFF'),
  ('BRA', 'Brazil', '🇧🇷', 'CONMEBOL', '#009B3A', '#FFDF00'),
  ('ARG', 'Argentina', '🇦🇷', 'CONMEBOL', '#75AADB', '#F6B40E'),
  ('URU', 'Uruguay', '🇺🇾', 'CONMEBOL', '#5CBFEB', '#FCD116'),
  ('COL', 'Colombia', '🇨🇴', 'CONMEBOL', '#FCD116', '#003893'),
  ('ECU', 'Ecuador', '🇪🇨', 'CONMEBOL', '#FFD100', '#034EA2'),
  ('PER', 'Peru', '🇵🇪', 'CONMEBOL', '#D91023', '#FFFFFF'),
  ('PAR', 'Paraguay', '🇵🇾', 'CONMEBOL', '#D52B1E', '#0038A8'),
  ('ENG', 'England', '🏴', 'UEFA', '#FFFFFF', '#C8102E'),
  ('FRA', 'France', '🇫🇷', 'UEFA', '#1D3F8F', '#EF4135'),
  ('ESP', 'Spain', '🇪🇸', 'UEFA', '#C60B1E', '#FFC400'),
  ('GER', 'Germany', '🇩🇪', 'UEFA', '#000000', '#DD0000'),
  ('POR', 'Portugal', '🇵🇹', 'UEFA', '#006600', '#FF0000'),
  ('NED', 'Netherlands', '🇳🇱', 'UEFA', '#FF6C00', '#21468B'),
  ('BEL', 'Belgium', '🇧🇪', 'UEFA', '#000000', '#FDDA24'),
  ('ITA', 'Italy', '🇮🇹', 'UEFA', '#0066CC', '#FFFFFF'),
  ('CRO', 'Croatia', '🇭🇷', 'UEFA', '#FF0000', '#FFFFFF'),
  ('SUI', 'Switzerland', '🇨🇭', 'UEFA', '#FF0000', '#FFFFFF'),
  ('DEN', 'Denmark', '🇩🇰', 'UEFA', '#C8102E', '#FFFFFF'),
  ('POL', 'Poland', '🇵🇱', 'UEFA', '#DC143C', '#FFFFFF'),
  ('NOR', 'Norway', '🇳🇴', 'UEFA', '#BA0C2F', '#00205B'),
  ('SWE', 'Sweden', '🇸🇪', 'UEFA', '#006AA7', '#FECC00'),
  ('AUT', 'Austria', '🇦🇹', 'UEFA', '#ED2939', '#FFFFFF'),
  ('SRB', 'Serbia', '🇷🇸', 'UEFA', '#C6363C', '#0C4076'),
  ('JPN', 'Japan', '🇯🇵', 'AFC', '#BC002D', '#FFFFFF'),
  ('KOR', 'South Korea', '🇰🇷', 'AFC', '#003478', '#C60C30'),
  ('AUS', 'Australia', '🇦🇺', 'AFC', '#00843D', '#FFCD00'),
  ('IRN', 'Iran', '🇮🇷', 'AFC', '#239F40', '#DA0000'),
  ('KSA', 'Saudi Arabia', '🇸🇦', 'AFC', '#006C35', '#FFFFFF'),
  ('QAT', 'Qatar', '🇶🇦', 'AFC', '#8A1538', '#FFFFFF'),
  ('UZB', 'Uzbekistan', '🇺🇿', 'AFC', '#0099B5', '#1EB53A'),
  ('IRQ', 'Iraq', '🇮🇶', 'AFC', '#CE1126', '#007A3D'),
  ('MAR', 'Morocco', '🇲🇦', 'CAF', '#C1272D', '#006233'),
  ('SEN', 'Senegal', '🇸🇳', 'CAF', '#00853F', '#FDEF42'),
  ('EGY', 'Egypt', '🇪🇬', 'CAF', '#CE1126', '#000000'),
  ('NGA', 'Nigeria', '🇳🇬', 'CAF', '#008751', '#FFFFFF'),
  ('CMR', 'Cameroon', '🇨🇲', 'CAF', '#007A3D', '#CE1126'),
  ('GHA', 'Ghana', '🇬🇭', 'CAF', '#CE1126', '#FCD116'),
  ('TUN', 'Tunisia', '🇹🇳', 'CAF', '#E70013', '#FFFFFF'),
  ('ALG', 'Algeria', '🇩🇿', 'CAF', '#006233', '#FFFFFF'),
  ('CIV', 'Ivory Coast', '🇨🇮', 'CAF', '#F77F00', '#009E60'),
  ('NZL', 'New Zealand', '🇳🇿', 'OFC', '#0033A0', '#FFFFFF')
on conflict (code) do update set
  name = excluded.name,
  flag_emoji = excluded.flag_emoji,
  confederation = excluded.confederation,
  primary_color = excluded.primary_color,
  secondary_color = excluded.secondary_color;

-- Mark the 2026 World Cup field. Verified against the seeded nations (48 teams).
update public.nations set in_world_cup_2026 = true
where code in (
  'USA','MEX','CAN','CRC','PAN','JAM','HON',
  'BRA','ARG','URU','COL','ECU','PER','PAR',
  'ENG','FRA','ESP','GER','POR','NED','BEL','ITA','CRO','SUI','DEN','POL','NOR','SWE','AUT','SRB',
  'JPN','KOR','AUS','IRN','KSA','QAT','UZB','IRQ',
  'MAR','SEN','EGY','NGA','CMR','GHA','TUN','ALG','CIV',
  'NZL'
);
